require: rubocop-rails
AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{bundle,rails,rake}"
    - "vendor/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
  NewCops: enable
