require: rubocop-rails
AllCops:
  Include:
    - "**/*.rb"
  Exclude:
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - bin/bundle
    - config/application.rb
    - app/models/application_record.rb
